#!/bin/bash

echo "=== Parallels Windows 文件访问指南 ==="
echo ""
echo "你的虚拟机位置："
echo "  ~/Parallels/Windows 11 (1).pvm/"
echo ""
echo "方法 1: 使用共享文件夹（推荐）"
echo "  1. 启动 Windows 虚拟机"
echo "  2. 在 Windows 中，打开文件资源管理器"
echo "  3. 导航到: C:\\Users\\lzc\\AppData\\Local\\Programs\\geo\\"
echo "  4. 复制文件到 Z:\\ 盘（这是你的 Mac Home 目录）"
echo "  5. 在 Mac 的 ~/  目录下就能看到复制的文件"
echo ""
echo "方法 2: 挂载虚拟磁盘（需要关闭虚拟机）"
echo "  运行以下命令："
echo "  /Applications/Parallels\\ Desktop.app/Contents/MacOS/prl_disk_tool mount \\"
echo "    --hdd ~/Parallels/\"Windows 11 (1).pvm\"/harddisk.hdd"
echo ""
echo "方法 3: 查看当前挂载的共享文件夹"
ls -la /Volumes/ 2>/dev/null | grep -i "parallels\|psf" || echo "  (当前没有挂载的共享文件夹)"
echo ""
echo "提示: 如果要查找 GEO 应用的配置文件，通常在："
echo "  Windows: C:\\Users\\lzc\\AppData\\Roaming\\geo\\"
echo "  (不是 Programs 目录，而是 Roaming 目录)"
