#!/bin/bash

echo "📊 批次定时发布间隔测试"
echo "================================"
echo ""

echo "1️⃣ 查看最近的批次任务执行情况"
echo "--------------------------------"
node check-batch-intervals.js

echo ""
echo "2️⃣ 监控服务器日志（批次相关）"
echo "--------------------------------"
echo "提示：创建新的批次任务后，观察日志输出"
echo "命令：tail -f server.log | grep -E '批次|等待|间隔|任务.*完成'"
echo ""

echo "3️⃣ 测试步骤"
echo "--------------------------------"
echo "在Windows端执行以下操作："
echo ""
echo "  1. 打开发布任务页面"
echo "  2. 选择 2 篇文章"
echo "  3. 选择 2 个平台（共4个任务）"
echo "  4. 设置间隔时间：3 分钟"
echo "  5. 点击「创建发布任务」"
echo ""
echo "  预期结果："
echo "  - 任务1：立即执行"
echo "  - 任务2：任务1完成后等待3分钟再执行"
echo "  - 任务3：任务2完成后等待3分钟再执行"
echo "  - 任务4：任务3完成后等待3分钟再执行"
echo ""

echo "4️⃣ 验证方法"
echo "--------------------------------"
echo "执行以下命令查看实际间隔："
echo ""
echo "  node -e \""
echo "  const { pool } = require('./server/dist/db/database');"
echo "  async function check() {"
echo "    const result = await pool.query(\`"
echo "      SELECT id, batch_order, status, updated_at"
echo "      FROM publishing_tasks"
echo "      WHERE batch_id = (SELECT batch_id FROM publishing_tasks ORDER BY created_at DESC LIMIT 1)"
echo "      ORDER BY batch_order"
echo "    \`);"
echo "    console.log('任务执行时间：');"
echo "    result.rows.forEach((row, i) => {"
echo "      const time = new Date(row.updated_at).toLocaleTimeString('zh-CN');"
echo "      console.log(\`  任务\${i+1}: \${time} (\${row.status})\`);"
echo "      if (i > 0) {"
echo "        const prev = new Date(result.rows[i-1].updated_at);"
echo "        const curr = new Date(row.updated_at);"
echo "        const interval = (curr - prev) / 60000;"
echo "        console.log(\`    间隔: \${interval.toFixed(2)}分钟\`);"
echo "      }"
echo "    });"
echo "    await pool.end();"
echo "  }"
echo "  check();"
echo "  \""
echo ""

echo "5️⃣ 实时监控命令"
echo "--------------------------------"
echo "在另一个终端执行："
echo ""
echo "  tail -f server.log | grep --color=auto -E '批次|等待|间隔|任务.*完成|⏳|✅'"
echo ""

echo "================================"
echo "✅ 测试准备完成"
echo ""
