#!/bin/bash

echo "======================================"
echo "企鹅号适配器测试"
echo "======================================"
echo ""

echo "请按照以下步骤测试："
echo ""
echo "1. 打开浏览器控制台（F12）"
echo "2. 切换到 Network 标签"
echo "3. 点击发布任务按钮"
echo "4. 查看是否有 POST /api/publishing/tasks 请求"
echo ""
echo "如果没有请求："
echo "  - 检查按钮是否正确绑定事件"
echo "  - 检查浏览器控制台是否有JavaScript错误"
echo ""
echo "如果有请求但失败："
echo "  - 查看请求的响应内容"
echo "  - 查看服务器日志"
echo ""
echo "如果请求成功但没有执行："
echo "  - 查看服务器日志中是否有任务执行记录"
echo "  - 检查任务状态"
echo ""
echo "======================================"
echo "手动测试API（需要替换参数）"
echo "======================================"
echo ""
echo "# 1. 获取token（登录后在浏览器控制台执行）"
echo "localStorage.getItem('token')"
echo ""
echo "# 2. 创建发布任务"
echo "curl -X POST http://localhost:3000/api/publishing/tasks \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"article_id\": 1,"
echo "    \"account_id\": 1,"
echo "    \"platform_id\": \"qie\""
echo "  }'"
echo ""
echo "# 3. 查看任务列表"
echo "curl -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "  'http://localhost:3000/api/publishing/tasks?page=1&pageSize=10'"
echo ""
echo "# 4. 手动执行任务（如果任务创建了但未执行）"
echo "curl -X POST http://localhost:3000/api/publishing/tasks/TASK_ID/execute \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN'"
echo ""
echo "======================================"
