#!/bin/bash

echo "=========================================="
echo "🔧 头条号登录选择器修复测试"
echo "=========================================="
echo ""

echo "📝 步骤 1: 执行数据库迁移..."
cd server
npx ts-node src/db/run-migration-009.ts

if [ $? -eq 0 ]; then
  echo ""
  echo "✅ 数据库迁移成功！"
  echo ""
  echo "=========================================="
  echo "📋 修复说明"
  echo "=========================================="
  echo ""
  echo "问题原因："
  echo "  Windows 登录管理器从后端 API 获取平台配置时，"
  echo "  数据库中缺少 'selectors' 字段，导致无法提取用户信息。"
  echo ""
  echo "修复内容："
  echo "  1. ✅ 添加 selectors 字段（JSONB 类型）"
  echo "  2. ✅ 添加 login_url 字段"
  echo "  3. ✅ 配置头条号的 7 个用户名选择器"
  echo "  4. ✅ 配置头条号的 3 个登录成功检测选择器"
  echo "  5. ✅ 同时更新了其他 11 个平台的配置"
  echo ""
  echo "头条号选择器优先级："
  echo "  1. .auth-avator-name (最精确)"
  echo "  2. .user-name"
  echo "  3. .username"
  echo "  4. .account-name"
  echo "  5. [class*=\"username\"] (通配符)"
  echo "  6. [class*=\"user-name\"] (通配符)"
  echo "  7. .semi-navigation-header-username (通用)"
  echo ""
  echo "=========================================="
  echo "🧪 测试步骤"
  echo "=========================================="
  echo ""
  echo "1. 重启后端服务器："
  echo "   cd server && npm run dev"
  echo ""
  echo "2. 重启 Windows 登录管理器："
  echo "   cd windows-login-manager && npm run dev"
  echo ""
  echo "3. 在 Windows 登录管理器中测试头条号登录："
  echo "   - 点击「平台管理」"
  echo "   - 选择「头条号」"
  echo "   - 点击「登录」按钮"
  echo "   - 完成登录后，应该能成功提取用户名"
  echo ""
  echo "4. 检查日志输出："
  echo "   - 应该看到「User info extracted: [用户名]」"
  echo "   - 不应该再看到「Failed to extract user information」"
  echo ""
  echo "=========================================="
  echo "✅ 修复完成！"
  echo "=========================================="
else
  echo ""
  echo "❌ 数据库迁移失败，请检查错误信息"
  exit 1
fi
